### ISSUE TITLE
Undefined reference to SetWindowSubclass (WinAPI)

### ISSUE THREAD

**Issue by Glacier2418** [skylee03/My-Dev-Cpp#2]
I'm learning WinAPI and on a tutorial there was explanation of subclassing. When I tried compiling on;

Bloodshed Dev-C++ 4.9.9.2
Orwell Dev-C++ 5.11
Your Dev-C++ 5.13

gives the error on the title with;

TDM GCC 4.9.2
MinGW GCC 7.5.0
MinGW GCC 8.1.0
MinGW GCC 9.2.0
MinGW GCC 10.1.0

So as you see, I've tried everything. Then I realized that the subclassing tutorial author was using Code::Blocks IDE, so I downloaded it. On **Code::Blocks with MinGW GCC 8.1.0 it compiles** perfectly fine. (It'll probably compile fine with other versions of GCC as well on Code::Blocks.) The point is, I configured compiler settings and project settings all the same so that made me thought that maybe Dev-C++ releases has some problems with something. I didn't know there might be **IDE-specific issues** but this seems the case. Can you please take a look at it? I don't wanna switch to Code::Blocks just because of this.

**Comment by Specher** [comment]
都是中国人能不能写中文

**Comment by skylee03** [comment]
Since you did not provided your source code, I tried to compile [this program](https://paste.ubuntu.com/p/6zjGqY3X7g/) (which could be seen in [a WinAPI tutorial on YouTube](https://www.youtube.com/watch?v=XWS8hPcEW_8)) with My Dev-C++, but I failed to reproduce the very problem you encountered. Have you create your project properly by using "Windows Application" as the project template? If not, please try to do it.

**Comment by Glacier2418** [comment]
I did what you suggested, created from the "Windows Application" project template, then copy-pasted the code you'd given. The result is same:

C:\Dev-Cpp\Compilers\9.2.0\x86_64-w64-mingw32\bin\ld.exe	C:\Users\ADMIN\AppData\Local\Temp\ccuGatjj.o:den.cpp:(.text+0x115): undefined reference to `DefSubclassProc'
C:\Dev-Cpp\Compilers\9.2.0\x86_64-w64-mingw32\bin\ld.exe	C:\Users\ADMIN\AppData\Local\Temp\ccuGatjj.o:den.cpp:(.text+0x24e): undefined reference to `SetWindowSubclass'
C:\Users\ADMIN\Desktop\den\collect2.exe	[Error] ld returned 1 exit status

Also there's no other feature that I cannot use properly. Only this subclassing fails. (And it only fails on Dev-C++ IDE)
