### ISSUE TITLE
Please have a look at BanzhuSoft's multilingual Dev-C++

### ISSUE THREAD

**Issue by banzhusoft** [skylee03/My-Dev-Cpp#3]
I am glad and somewhat surprise to find this project.
However, I have released a new and updated fork of Dev-C++.

Please have a look at BanzhuSoft's multilingual Dev-C++:
https://banzhusoft.github.io (in English)
https://sourceforge.net/projects/devcpp20/ (in English)
https://banzhusoft.github.io/devcpp-cn/ (in Chinese)

**Comment by WuZhengqiang666** [comment]
感谢你们
